version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    depends_on:
      - db
    networks:
      - techfood-network

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: techfood_payment
      MYSQL_USER: techfood
      MYSQL_PASSWORD: techfood
    ports:
      - "3308:3306"
    networks:
      - techfood-network

networks:
  techfood-network:
    external: true
