database:
  username: ${DATABASE_USER}
  password: ${DATABASE_PASSWORD}
  url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
  driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update