server:
    port: 8081
spring:
    datasource:
        url: ${database.url}
        username: ${database.username}
        password: ${database.password}
        driver-class-name: ${database.driver-class-name}
    profiles:
        active: ${APP_PROFILE:dev}
    cloud:
        aws:
            region:
                static: us-east-1
            credentials:
                access-key: ${AWS_ACCESS_KEY}
                secret-key: ${AWS_SECRET_KEY}

production:
    url: ${production.url}

events:
    output: "arn:aws:sns:us-east-1:027260563052:created_orders_topic"
    queues:
        created-order: "created_order_ms_payment_queue"
