database:
  username: techfood
  password: techfood
  url: jdbc:mysql://db:3306/techfood_payment
  driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

production:
  url: "https://z2l3q.wiremockapi.cloud/production"


 # Senha:  hc7GNsj8wAim1uQ2h6az
 # User: admin