spring:
    datasource:
        url: ${database.url}
        username: ${database.username}
        password: ${database.password}
        driver-class-name: ${database.driver-class-name}

production:
    url: ${production.url}
