database:
    username: techfood
    password: techfood
    url: jdbc:mysql://localhost:3306/techfood
    driver-class-name: com.mysql.cj.jdbc.Driver

spring:
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update

production:
    url: "http://192.168.0.3:8584/version"